<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="true" />

<title>HDAT9600 Course review and best practice tips</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->


<link rel="stylesheet" href="css/tutorials.css" type="text/css" />

</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<p><img src="images/UNSW_2017_Big_Data_landscape.jpg" style="width:75.0%" /></p>
<div id="section-introduction" class="section level2">
<h2>Introduction</h2>
<p><span class="copyright">© Copyright 2021 UNSW Sydney. All rights reserved except where otherwise stated.</span></p>
<p><br></p>
<p>In statistics courses, a lot of time is spent teaching the specific detail of how to conduct different types of regression analyses with data that is perfectly designed for the analysis of interest. However, in practice during your Health Data Science career, you will likely receive messy data and be faced with the big question: which is the appropriate type of analysis? This will depend on your research question and the type of data you have. Once the appropriate model is chosen, you will commence the process of ‘model building’ i.e. determining which variables to include or exclude during your analysis, and in what order.</p>
<p>Once your analysis is complete, you begin the task of communicating the results to others. To do this you need to be able to identify the most important components of your statistical output, and present them in such a way that the reader can correctly interpret your results. Each of these tasks is a learned skill that takes practice.</p>
<p>In this chapter we present an overview of some best-practice tips for conducting statistical analyses. We will cover methods for choosing the appropriate statistical model, and model building principles, including information to help you select covariates. We conclude the chapter with guidelines for presenting and reporting your results.</p>
</div>
<div id="section-choosing-the-model" class="section level2">
<h2>Choosing the model</h2>
<p>As you have seen in thus far, we make a distinction about model types based on our outcome of interest (to a point, if repeat measures are involved there are other models which we haven’t covered in this course. More on these in HDAT9700 Statistical Modelling II). With that in mind, choosing a model comes down to a few additional questions. Here’s a simplified flowchart outlining the model types, based on the outcomes of interest.</p>
<div class="figure">
<img src="images/Model_flowchart_portrait.png" style="width:90.0%" alt="" />
<p class="caption">Regression models flowchart - portrait mode</p>
</div>
<div id="section-activity" class="section level3">
<h3>Activity</h3>
<p>For each of the research questions below, use the Regression Models flowchart to identify the correct methods of analysis.</p>
<ol style="list-style-type: decimal">
<li><p>Among a group of children being treated for acute lymphoblastic leukaemia, is cranial radiation (yes/no) associated with increased BMI (standarsised) z-score?</p></li>
<li><p>Among a population of chronically-ill patients in Sydney (age 60+), does participation in a coordinated care intervention (two groups: intervention vs. usual care) reduce the number of emergency department re-presentations?</p></li>
<li><p>For people living with HIV in Vietnam, what are the demographic and clinical factors (e.g. age, sex, location, BMI) that predict time to initiation of treatment with antiretroviral therapy?</p></li>
<li><p>Among a group of Australian men, does alcohol consumption (in units/day) predict the risk of developing the condition Barrett’s Oesophagus (yes/no)?</p></li>
</ol>
</div>
</div>
<div id="section-model-building" class="section level2">
<h2>Model building</h2>
<p>We have already mentioned model building in previous chapters, but let’s take some time to delve a little deeper into this topic.</p>
<p>You might have heard the saying “Rome wasn’t built in a day” – and the same can be said for building a statistical model. This task varies depending on a dataset and the variables it contains, analysts’ experience and knowledge of the field. And plenty of iterations, checking, interpreting and testing.</p>
<p>Now, there are automated ways of model building and selection (you may have come across <a href="https://en.wikipedia.org/wiki/Stepwise_regression">stepwise selection</a> or forward and backward selection procedure). But don’t get fooled by their ease of use. The rigour and thought of manual model building cannot be replaced by the machine (unless we want to fit the best prediction model and use machine learning techniques). So you can use stepwise methods as a guide only, but you still need to make iterative decisions yourself.</p>
<p>Model building is an artform, and there are no set ‘rules’ about ways of going about it. The choice of the next step is dependent on the findings of the preceding one, and there are numerous checks and tests to perform at each stage. Thus, while we can provide some guidance, the rest of the creativity comes down to you:</p>
<ol style="list-style-type: decimal">
<li><p>Always, always, think about your <strong>research question</strong>. Keep on revisiting the purpose of your analysis and revisit why you are doing the modelling. It’s very easy to get lost in the data and start finding interesting relationships, but if they are leading you into a rabbit hole, step back, and remember your research question.</p></li>
<li><p>Think about the <strong>predictors</strong> themselves and try to group them into meaningful groups (to help guide the interpretations). Epidemiologists often use a conceptual model such as the <a href="https://en.wikipedia.org/wiki/Andersen_healthcare_utilization_model">Anderson Healthcare Utilization Model</a>, in which an individuals’ access to healthcare services is determined by three factors. These are:</p></li>
</ol>
<ul>
<li>Predisposing factors (individuals’ socio-cultural characteristics including demographics, social structure and health beliefs)</li>
<li>Enabling factors (factors impacting on obtaining care)</li>
<li>Need (functional and health problems leading to the use of health services).</li>
</ul>
<p>But you can also think in simpler structures such as:</p>
<ul>
<li>Sociodemographic information – age, sex, school attainment, socio-economic factors</li>
<li>Health status – present chronic or acute conditions, self-rated health</li>
<li>Risk factors – smoking, obesity, alcohol and drug use etc</li>
<li>Etc.</li>
</ul>
<p>These sets of variables can help you in understanding and interpreting correlations and multicollinearity. An example of correlated variables might be patient’s geographical location of residence (e.g. Access/Remoteness Index of Australia (ARIA) – major city, inner and regional areas, remote and very remote areas) and area’s sociodemographic status (e.g. SEIFA decile – low to high disadvantage area). As the two measures are correlated, analysts usually include one or the other variable in the model, but not both simultaneously.</p>
<ol start="3" style="list-style-type: decimal">
<li><p>We stressed the importance of the <strong>exploratory data analysis (EDA)</strong> over and over in the course. Even if you think you may know the data well, it’s always a good idea to plot the data first and examine its characteristics. We can quickly get a sense of the distribution and any outlying observations, as well as any ambiguities in the dataset. Do not underestimate the power of descriptive statistics.</p></li>
<li><p>Check the association between the outcome and each individual variable (<strong>univariate analysis</strong>). Here we can check whether there seems to be a relationship between variables and decide on the functional form. Here we also produce plots, as they can provide invaluable information about whether linear relationships are present, or you may need to consider nonlinearity. Estimate the model coefficients and note its size and significance, we’ll use this information iteratively in the next step.</p></li>
<li><p>Start putting the variables that you find are significantly associated with an outcome in <strong>multivariable model</strong>. Here we don’t just put the variables that are significant at 5% level, but those that are significant at even 10% or 20% level. Now that you’ve put a few significant variables in the model all at once, how have the model coefficients changed in size and significance? Test the overall significance of the model and evaluate its diagnostics.</p></li>
<li><p>At this stage you can start <strong>excluding non-significant variables</strong> from the previous step, and re-fitting the multivariable model with a possibly reduced variable set. Again, examine the significance of each of the variables in the model, and their joint significance. Evaluate the diagnostics again.</p></li>
<li><p>Check for <strong>interactions</strong> between variables – here we use our scientific knowledge to test for interactions which may be present. We add interactions one at the time and test its significance. If we find a significant interaction, we need to take care in interpreting the coefficients accordingly. Also, make sure that you don’t delete the component variables themselves! For example if we are testing an interaction between age and sex variables, we need to keep all three variables in the model (age, sex, age*sex) regardless of the significance of the age and sex variables themselves. The interpretation of the interaction is only possible if we have all component terms in there.</p></li>
<li><p><strong>Interpretation</strong>! Stop and ‘listen’ to the results. What are they telling you? Do they make sense and can you interpret them? Here we move beyond statistical significance and start examining the relationships quantitatively. Bear in mind that just because something has a significant p-value that it may not hold much importance clinically. Remember to interpret the model coefficients according to which model you fit – OR, RR, HR or something else.</p></li>
</ol>
<p>See – there is ‘art’ in model building and selection. And who says that statisticians can’t be creative?</p>
</div>
<div id="section-a-worked-example" class="section level2" data-progressive="TRUE">
<h2>A worked example</h2>
<p>This section presents a simple worked example loosely following the steps outlined in the previous section. Each subsection is progressively revealed; there are 8 subsections in all:</p>
<ul>
<li>The research question<br />
</li>
<li>Getting to know the data<br />
</li>
<li>Data preparation<br />
</li>
<li>Exploratory data analysis<br />
</li>
<li>Model building<br />
</li>
<li>Refining the model<br />
</li>
<li>Model interpretation<br />
</li>
<li>Calibration</li>
</ul>
<p>You will need about one hour to work through these carefully.</p>
<div id="section-the-research-question" class="section level3">
<h3>The research question</h3>
<p>Cardiac catherization is a medical procedure undertaken to diagnose cardiovascular conditions. The procedure involves inserting a narrow tube or catheter into the heart, via a blood vessel from the arm, neck or groin. Once the catheter is in place, measurements on the condition of the heart muscles, valves and vessels can be taken to identify coronary disease.</p>
<p>The aim of this exercise is to build a model that can usefully predict the presence of severe coronary disease using just three patient characteristics that can be easily assessed over the telephone: age, sex and duration of symptoms.</p>
<p>The data for this exerice are taken from the <code>acath</code> dataset which comes with the <code>rms</code> package. More information <a href="https://hbiostat.org/R/rms/">here</a>.</p>
<blockquote>
<p>This dataset is from the Duke University Cardiovascular Disease Databank and consists of 3504 patients and 6 variables. The patients were referred to Duke University Medical Center for chest pain. Severe coronary disease is defined as three-vessel or left main disease and is denoted by tvdlm=1.</p>
</blockquote>
<p>The variables in the dataset are:</p>
<p><code>sex</code> (0=Male, 1=Female)<br />
<code>age</code> (in years)<br />
<code>cad.dur</code> (Duration of Symptoms of Coronary Artery Disease, e.g. chest pain)<br />
<code>choleste</code> (Cholesterol)<br />
<code>sigdz</code> (Significant Coronary Disease by Cardiac Catherization)<br />
<code>tvdlm</code> (Three Vessel or Left Main Disease by Cardiac Catherization)</p>
<p>Two of these variables can be <strong>ignored</strong> for the the purposes of this exercise:<br />
1. <code>choleste</code> which contains a large number of missing observations (methods for handling missing data in regression analyses are covered in HDAT9700)<br />
2. <code>sigdz</code> which is an alternative classification of disease, also established through cardiac catherization.</p>
</div>
<div id="section-getting-to-know-the-data" class="section level3">
<h3>Getting to know the data</h3>
<p>We can read in the data as follows:</p>
<pre class="r"><code>library(&quot;Hmisc&quot;)
getHdata(acath)</code></pre>
<p>We will explore the data using the <code>head()</code> and <code>str()</code> functions</p>
<pre class="r"><code>head(acath)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["sex"],"name":[1],"type":["int"],"align":["right"]},{"label":["age"],"name":[2],"type":["labelled"],"align":["right"]},{"label":["cad.dur"],"name":[3],"type":["labelled"],"align":["right"]},{"label":["choleste"],"name":[4],"type":["labelled"],"align":["right"]},{"label":["sigdz"],"name":[5],"type":["labelled"],"align":["right"]},{"label":["tvdlm"],"name":[6],"type":["labelled"],"align":["right"]}],"data":[{"1":"0","2":"73","3":"132","4":"268","5":"1","6":"1","_rn_":"1"},{"1":"0","2":"68","3":"85","4":"120","5":"1","6":"1","_rn_":"2"},{"1":"0","2":"54","3":"45","4":"NA","5":"1","6":"0","_rn_":"3"},{"1":"1","2":"58","3":"86","4":"245","5":"0","6":"0","_rn_":"4"},{"1":"1","2":"56","3":"7","4":"269","5":"0","6":"0","_rn_":"5"},{"1":"0","2":"64","3":"0","4":"NA","5":"1","6":"0","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<ul>
<li>In the first six rows we can see some <em>NA</em> values for the variable <code>choleste</code></li>
</ul>
<hr />
<pre class="r"><code>str(acath)</code></pre>
<pre><code>## &#39;data.frame&#39;:    3504 obs. of  6 variables:
##  $ sex     : &#39;labelled&#39; int  0 0 0 1 1 0 0 0 0 0 ...
##  $ age     : &#39;labelled&#39; int  73 68 54 58 56 64 65 41 68 52 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Age&quot;
##   ..- attr(*, &quot;units&quot;)= chr &quot;Year&quot;
##  $ cad.dur : &#39;labelled&#39; int  132 85 45 86 7 0 76 15 30 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Duration of Symptoms of Coronary Artery Disease&quot;
##  $ choleste: &#39;labelled&#39; int  268 120 NA 245 269 NA NA 247 NA NA ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Cholesterol&quot;
##   ..- attr(*, &quot;units&quot;)= chr &quot;mg %&quot;
##  $ sigdz   : &#39;labelled&#39; int  1 1 1 0 0 1 1 1 1 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Significant Coronary Disease by Cardiac Cath&quot;
##  $ tvdlm   : &#39;labelled&#39; int  1 1 0 0 0 0 1 0 1 0 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Three Vessel or Left Main Disease by Cardiac Cath&quot;
##  - attr(*, &quot;comment&quot;)= chr &quot;Data from the Duke University Cardiovascular Disease Databank&quot;</code></pre>
<ul>
<li>The dataframe has 3,504 observations on six variables<br />
</li>
<li>The class of the variables is <code>labelled</code> which is a bit unusual</li>
</ul>
<hr />
<p>We can use <code>summary()</code> to get a quick overview of the variable distributions</p>
<pre class="r"><code>summary(acath)</code></pre>
<pre><code>##       sex              age           cad.dur       choleste    
##  Min.   :0.0000   Min.   :17.00   Min.   :  0   Min.   : 29.0  
##  1st Qu.:0.0000   1st Qu.:46.00   1st Qu.:  4   1st Qu.:196.0  
##  Median :0.0000   Median :52.00   Median : 18   Median :224.5  
##  Mean   :0.3136   Mean   :52.28   Mean   : 43   Mean   :229.9  
##  3rd Qu.:1.0000   3rd Qu.:59.00   3rd Qu.: 60   3rd Qu.:259.0  
##  Max.   :1.0000   Max.   :82.00   Max.   :416   Max.   :576.0  
##                                                 NA&#39;s   :1246   
##      sigdz            tvdlm       
##  Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :1.0000   Median :0.0000  
##  Mean   :0.6661   Mean   :0.3225  
##  3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000  
##                   NA&#39;s   :3</code></pre>
<ul>
<li>31% of patients are female<br />
</li>
<li>The median age is 52 years (range 17-82)<br />
</li>
<li>The median duration of symptoms is 18 days (range 0-416)<br />
</li>
<li>There are 1,246 obseravtions missing for <code>choleste</code><br />
</li>
<li>32% of patients had severe coronary disease (<code>tvdlm</code>)</li>
<li>There are 3 missing observations for <code>tvdlm</code></li>
</ul>
</div>
<div id="section-data-preparation" class="section level3">
<h3>Data preparation</h3>
<p>Elements of the provided data frame are not ideal for future analysis. Here we take a few steps to make an analysis-ready dataset, including:</p>
<ul>
<li>Drop the variable <code>choleste</code> which is incomplete and will not be used<br />
</li>
<li>Drop the variable <code>sigdz</code> which will not be used</li>
<li>Drop the 3 records with missing outcome data</li>
<li>We also mutate some variables to make them easier to work with if (e.g. add value labels for sex, change storage types)</li>
</ul>
<pre class="r"><code>acath2 = acath %&gt;% 
  select(-choleste, -sigdz) %&gt;% 
  filter(! is.na(tvdlm)) %&gt;% 
  mutate(tvdlm = as.integer(tvdlm)) %&gt;%
  mutate(sex = factor(sex, levels=c(0,1), labels = c(&quot;Male&quot;, &quot;Female&quot;))) %&gt;%
  mutate(cad.dur = as.integer(cad.dur)) %&gt;%
  mutate(age = as.integer(age))

summary(acath2)</code></pre>
<pre><code>##      sex            age           cad.dur           tvdlm       
##  Male  :2404   Min.   :17.00   Min.   :  0.00   Min.   :0.0000  
##  Female:1097   1st Qu.:46.00   1st Qu.:  4.00   1st Qu.:0.0000  
##                Median :52.00   Median : 18.00   Median :0.0000  
##                Mean   :52.27   Mean   : 42.97   Mean   :0.3225  
##                3rd Qu.:59.00   3rd Qu.: 60.00   3rd Qu.:1.0000  
##                Max.   :82.00   Max.   :416.00   Max.   :1.0000</code></pre>
</div>
<div id="section-exploratory-data-analysis" class="section level3">
<h3>Exploratory data analysis</h3>
<p>Before modelling can begin it is essential to understand the variables, their distribution and the relationships between them.</p>
<p>We’ve already used <code>summary()</code> to look at the univariate distribution of the four variables to be used in the analysis. Try using <code>histogram()</code> to get a better sense of the distribution of the continuous variables.</p>
<div class="tutorial-exercise" data-label="wex6" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="12">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>You should also examine the bivariate relationship between the predictor variables and the outcome. You could do this graphically or you could use a formal test.</p>
<div class="tutorial-exercise" data-label="wex7" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="12">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="wex7-hint" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># % diseased by sex
acath2 %&gt;% 
group_by(sex) %&gt;% 
summarise(mean=mean(tvdlm)) %&gt;%  
ggplot(aes(sex, mean)) + geom_col()

# % diseased by deciles of age
acath2 %&gt;% 
mutate(age2=cut(age,unique(quantile(age, seq(0,1,by=0.1))))) %&gt;%
group_by(age2) %&gt;% 
summarise(mean=mean(tvdlm)) %&gt;%  
ggplot(aes(age2, mean)) + geom_col()

# % diseased by deciles of symptom duration
acath2 %&gt;% 
mutate(cad.dur2=cut(cad.dur, unique(quantile(acath2$cad.dur, seq(0,1,by=0.1))))) %&gt;%
group_by(cad.dur2) %&gt;% 
summarise(mean=mean(tvdlm)) %&gt;%  
ggplot(aes(cad.dur2, mean)) + geom_col()</code></pre>
</div>
<p>Check for any interactions: does the relationship between age and disease differ for males and females for example?</p>
<div class="tutorial-exercise" data-label="wex8" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="12">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="wex8-hint" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># % diseased by deciles of age
acath2 %&gt;% 
mutate(age2=cut(age,unique(quantile(age, seq(0,1,by=0.1))))) %&gt;%
group_by(age2, sex) %&gt;% 
summarise(mean=mean(tvdlm)) %&gt;%  
ggplot(aes(age2, mean, fill=sex)) + geom_col(position=&quot;dodge&quot;)

# % diseased by deciles of symptom duration
acath2 %&gt;% 
mutate(cad.dur2=cut(cad.dur,unique(quantile(cad.dur, seq(0,1,by=0.1))))) %&gt;%
group_by(cad.dur2, sex) %&gt;% 
summarise(mean=mean(tvdlm), count=n()) %&gt;%  
ggplot(aes(cad.dur2, mean, fill=sex)) + geom_col(position=&quot;dodge&quot;)</code></pre>
</div>
<hr />
<p>Having explored the data you should be able to answer the following questions</p>
<div class="panel panel-default">
<div data-label="q1" class="tutorial-question panel-body">
<div id="q1-answer_container" class="shiny-html-output"></div>
<div id="q1-message_container" class="shiny-html-output"></div>
<div id="q1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="q2" class="tutorial-question panel-body">
<div id="q2-answer_container" class="shiny-html-output"></div>
<div id="q2-message_container" class="shiny-html-output"></div>
<div id="q2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
</div>
<div id="section-model-building-1" class="section level3">
<h3>Model building</h3>
<p>Now that we are more familiar with our data we can start to fit some simple models. Disease status is a binary outcome, so we will start with a logistic regression model (because the primary task here is prediction rather than explanation we won’t worry for now that odds ratios from a logistic regression will overstate the risk ratio). As a baseline model, consider the model with main effects for <code>sex</code>, <code>age</code> and <code>cad.dur</code>.</p>
<pre class="r"><code>m1 &lt;- glm(tvdlm ~ sex + age + cad.dur, family=binomial(link=logit), data=acath2)
summary(m1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = tvdlm ~ sex + age + cad.dur, family = binomial(link = logit), 
##     data = acath2)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2363  -0.8621  -0.5897   1.0897   2.6972  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -3.7486944  0.2316639 -16.182  &lt; 2e-16 ***
## sexFemale   -1.3691988  0.0963050 -14.217  &lt; 2e-16 ***
## age          0.0595757  0.0044014  13.536  &lt; 2e-16 ***
## cad.dur      0.0044239  0.0006733   6.571 5.01e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4402.3  on 3500  degrees of freedom
## Residual deviance: 3901.1  on 3497  degrees of freedom
## AIC: 3909.1
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp(coefficients(m1))</code></pre>
<pre><code>## (Intercept)   sexFemale         age     cad.dur 
##  0.02354847  0.25431063  1.06138615  1.00443366</code></pre>
<p>Above we can see that all three variables are significantly associated with the outcome and that the direction of the results are as we would expect from out exploratory analysis:</p>
<ul>
<li>The odds of severe disease was lower for women<br />
</li>
<li>The odds of severe disease increases with age<br />
</li>
<li>The odds of severe disease increases with duration of symptoms</li>
</ul>
<hr />
<p>Adapt the code above to explore interactions and non-linearities. Fit the following models:</p>
<ul>
<li>m2 = m1 + <code>age</code>:<code>sex</code> interaction</li>
<li>m3 = m1 + <code>cad.dur</code>:<code>age</code> interaction</li>
<li>m4 = m1 + <code>cad.dur</code>:<code>sex</code> interaction</li>
<li>m5 = m1 + quadratic term for <code>age</code></li>
<li>m6 = m1 + quadratic term for <code>cad.dur</code></li>
</ul>
<div class="tutorial-exercise" data-label="wex10" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="20">
<pre class="text"><code>m1 &lt;- glm(tvdlm ~ sex + age + cad.dur, family=binomial(link=logit), data=acath2)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="wex10-hint" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>m1 &lt;- glm(tvdlm ~ sex + age + cad.dur, family=binomial(link=logit), data=acath2)

m2 &lt;- glm(tvdlm ~ sex + age + cad.dur + age:sex, family=binomial(link=logit), data=acath2)

m3 &lt;- glm(tvdlm ~ sex + age + cad.dur + cad.dur:age, family=binomial(link=logit), data=acath2)

m4 &lt;- glm(tvdlm ~ sex + age + cad.dur + cad.dur:sex, family=binomial(link=logit), data=acath2)

m5 &lt;- glm(tvdlm ~ sex + age + cad.dur + I(age^2), family=binomial(link=logit), data=acath2)

m6 &lt;- glm(tvdlm ~ sex + age + cad.dur + I(cad.dur^2), family=binomial(link=logit), data=acath2)

lapply(list(m2,m3,m4,m5,m6) , function(x) {print(anova(m1,x, test=&quot;Chisq&quot;))} )</code></pre>
</div>
<div class="panel panel-default">
<div data-label="q3" class="tutorial-question panel-body">
<div id="q3-answer_container" class="shiny-html-output"></div>
<div id="q3-message_container" class="shiny-html-output"></div>
<div id="q3-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="q4" class="tutorial-question panel-body">
<div id="q4-answer_container" class="shiny-html-output"></div>
<div id="q4-message_container" class="shiny-html-output"></div>
<div id="q4-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
</div>
<div id="section-refining-the-model" class="section level3">
<h3>Refining the model</h3>
<p>If you have worked thorugh the previous section, you should have seen that there is evidence for a non-linear effect of symptom duration, and also evidence for an interaction between symptom duration and sex. Let’s revisit the exploratory data analysis to understand what is going on between sex, symptom duration and the risk of severe disease.</p>
<pre><code>## `summarise()` has grouped output by &#39;cad.dur2&#39;. You can override using the `.groups` argument.</code></pre>
<p><img src="review_files/figure-html/wex11-1.png" width="624" /></p>
<p>We can see that</p>
<ul>
<li>For the whole population, the risk appears to flatten slightly after 60-90 days symptom duration<br />
</li>
<li>This is most pronounced for men<br />
</li>
<li>Among women, the relationship between severe disease and symptom duration is much flatter</li>
</ul>
<p>Based on these observations, let’s try two more models:</p>
<ul>
<li>m7 = m1 + <code>sex</code>:<code>cad.dur</code> interaction + quadratic term for <code>cad.dur</code><br />
</li>
<li>m8 = m1 + <code>sex</code>:<code>cad.dur</code> interaction + quadratic term for <code>cad.dur</code> + age:<code>cad.dur</code>^2 interaction</li>
</ul>
<p>The model <strong>m7</strong> allows for the effect of symptom duration to be non-linear, and it allows the fitted curve to vary for males and females, but the curvature must be the same. In contrast, <strong>m8</strong> allows the curvature for males and females to differ.</p>
<p>Run the code below to fit the two additional models. Add your own code to examine the models and test if they improve on earlier ones.</p>
<div class="tutorial-exercise" data-label="wex12" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="20">
<pre class="text"><code># Assume non-linear sex-duration interation (same curvature for male and female)
m7 &lt;- glm(tvdlm ~ age + sex + cad.dur + cad.dur:sex + I(cad.dur^2), data=acath2, family=binomial(link=logit))

# Assume non-linear sex-duration interation (different curvature for male and female)
m8 &lt;- glm(tvdlm ~ age + sex + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
</div>
<div id="section-model-interpretation" class="section level3">
<h3>Model interpretation</h3>
<p>So far we’ve only had a cursory examination of the model output. Lets have a closer look at estiamted parameters from model 8 and makes sure we can interpret them ok.</p>
<pre class="r"><code># Assume non-linear sex-duration interation (different curvature for male and female)
m8 &lt;- glm(tvdlm ~ age + sex + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))

summary(m8)</code></pre>
<pre><code>## 
## Call:
## glm(formula = tvdlm ~ age + sex + cad.dur + cad.dur:sex + I(cad.dur^2) + 
##     I(cad.dur^2):sex, family = binomial(link = logit), data = acath2)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0317  -0.8368  -0.5890   1.0397   2.6316  
## 
## Coefficients:
##                          Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)            -3.917e+00  2.361e-01 -16.587  &lt; 2e-16 ***
## age                     5.918e-02  4.424e-03  13.377  &lt; 2e-16 ***
## sexFemale              -1.001e+00  1.382e-01  -7.239 4.52e-13 ***
## cad.dur                 1.226e-02  1.782e-03   6.881 5.95e-12 ***
## I(cad.dur^2)           -3.056e-05  7.647e-06  -3.996 6.43e-05 ***
## sexFemale:cad.dur      -1.045e-02  3.561e-03  -2.934  0.00335 ** 
## sexFemale:I(cad.dur^2)  2.492e-05  1.393e-05   1.788  0.07374 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4402.3  on 3500  degrees of freedom
## Residual deviance: 3871.2  on 3494  degrees of freedom
## AIC: 3885.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The intercept is -3.9 on the log odds scale. This means that for the baseline individual, the log odds of severe coronary disease is <span class="math inline">\(-3.9\)</span>, the odds of severe disease is <span class="math inline">\(e^{-3.9} = 0.02\)</span> and the probability of severe disease is <span class="math inline">\((e^{-(-3.9)}+1)^{-1} = 0.02\)</span>, or 2%. This seems remarkably low. We know from our EDA that around 32% of patients in the sample have severe coronary disease.</p>
<p>So who is this “baseline” patient with very low risk? The baseline patient is the observation where each of the predictors is set to zero (for continuous variables) or the baseline category (for categorical variables). For our model above, the baseline patient is a male, aged 0 with 0 days cardiac symptoms. We’ve prediceted the risk for a newborn baby! This is obviously not very useful, and also completely invalid, given that our sample only contained adults. Making predictions based on values which lie far outside the range of the observed data is called extrapolation and is bad practice.</p>
<p>We can mean-centre the age variable to get more sensible predictions. This means that the baseline age will be the average age in the sample: 52 years. At the same time, lets set the baseline category for <code>sex</code> to be the low-risk group, i.e. females. In a normal analysis you would probably make these changes as part of the data cleaning but here the are done directly in the model.</p>
<pre class="r"><code># Assume non-linear sex-duration interation (different curvature for male and female)
m8b &lt;- glm(tvdlm ~ I(age-52) + relevel(sex, ref = &quot;Female&quot;) + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))

summary(m8b)</code></pre>
<pre><code>## 
## Call:
## glm(formula = tvdlm ~ I(age - 52) + relevel(sex, ref = &quot;Female&quot;) + 
##     cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, 
##     family = binomial(link = logit), data = acath2)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0317  -0.8368  -0.5890   1.0397   2.6316  
## 
## Coefficients:
##                                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                      -1.840e+00  1.218e-01 -15.105  &lt; 2e-16 ***
## I(age - 52)                       5.918e-02  4.424e-03  13.377  &lt; 2e-16 ***
## relevel(sex, ref = &quot;Female&quot;)Male  1.001e+00  1.382e-01   7.239 4.52e-13 ***
## cad.dur                           1.226e-02  1.782e-03   6.881 5.95e-12 ***
## I(cad.dur^2)                     -3.056e-05  7.647e-06  -3.996 6.43e-05 ***
## cad.dur:sexFemale                -1.045e-02  3.561e-03  -2.934  0.00335 ** 
## sexFemale:I(cad.dur^2)            2.492e-05  1.393e-05   1.788  0.07374 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4402.3  on 3500  degrees of freedom
## Residual deviance: 3871.2  on 3494  degrees of freedom
## AIC: 3885.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="aside">
<h3 id="section-aside">Aside</h3>
<p>Note that while these changes will make the model parameters easier to interpret, nothing has changed in a statistcal sense. We can see this if we formally compare model 8 to model 8b:</p>
<pre class="r"><code># Assume non-linear sex-duration interation (different curvature for male and female)
m8 &lt;- glm(tvdlm ~ age + sex + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))
m8b &lt;- glm(tvdlm ~ I(age-52) + relevel(sex, ref = &quot;Female&quot;) + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))

print(anova(m8,m8b,test=&quot;Chisq&quot;))</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: tvdlm ~ age + sex + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex
## Model 2: tvdlm ~ I(age - 52) + relevel(sex, ref = &quot;Female&quot;) + cad.dur + 
##     cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
## 1      3494     3871.2                     
## 2      3494     3871.2  0        0</code></pre>
</div>
<p><strong>Baseline</strong> Returning to the interpretation of model 8b, the intercept is now -1.824. This means that for the baseline individual (a 52 year old women, with 0 days symptoms) the odds of severe disease is <span class="math inline">\(e^{-1.824} = 0.16\)</span> and the probability of severe disease is <span class="math inline">\((e^{-(-1.824)}+1)^{-1} = 0.19\)</span>, or 19%. This seems more sensible.</p>
<p><strong>Age</strong><br />
The estimated parameter for <code>age</code> is 0.0592 which means that the odds of severe disease increases be an estimated <span class="math inline">\(e^{0.0592} = 1.06\)</span> or around 6% for each additional year of age after 52 years.</p>
<p><strong>Sex</strong><br />
The estimated parameter for <code>sex</code> is 1.0 on the log odds scale. The baseline group is female, which means that the estimated increased odds of disease for men relative to women is <span class="math inline">\(e^{1.0} = 2.7\)</span>. Because the model includes other terms interacting with <code>sex</code> this estimate refers to the case when those terms are 0, i.e. when symptom duration <code>cad.dur</code> is 0 days.</p>
<p>Thinking back to the EDA section, we saw that the risk of severe disease was about twice as high for men versus women. The estimated odds ratio of 2.7 is a bit higher than our intuitive sense that the risk is twice as high in men. Try adapting the code to fit a modified Poisson model instead of a logistic regression in the code block below. Recall that the modified Poisson assumes a Poisson distribution with a log link. How does the estimated risk ratio for males versus females from the modified Poisson model compare to the corresponding estimated odds from the logistic regression? Can you remember what is going on here? (See Chapter 6).</p>
<pre class="r"><code>m8b &lt;- glm(tvdlm ~ I(age-52) + relevel(sex, ref = &quot;Female&quot;) + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))</code></pre>
<p><strong>Symptom duration</strong> Interpreting interaction effects directly from model coefficients is difficult, but as a starting point we can use the magnitude and sign (i.e. positive or negative) of the parameter estimates to understand the shape of the fitted curve for the relationship between symptom duration, sex and risk of disease.</p>
<p>The main effect for symptom duration <code>cad.dur</code> is positive and the quadratic term is negative but much smaller. This suggests that the relationship between symptom duration and disease in men (the baseline group) is positive but tapers off as sypmtom duration increases.</p>
<p>Visualising predicted values from our model is great way to help us understand and interpret interaction estimates. Lets have a look at predicted risk for men and women by sypmtom duration. To make things simpler, we will just look at the relationship at ages 30, 40, 50, and 60 years.</p>
<pre class="r"><code>m8b &lt;- glm(tvdlm ~ I(age-52) + relevel(sex, ref = &quot;Female&quot;) + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))

acath2 %&gt;%
  mutate(pred = predict(m8b, type=&quot;response&quot;)) %&gt;%
  filter(age %in% c(30,40,50,60,70)) %&gt;%
  ggplot(aes(cad.dur, pred)) + 
  geom_point(aes(col=sex)) + 
  facet_grid(rows=vars(age)) + 
  labs(y=&quot;Predicted probabilty of severe coronary disease&quot;, x = &quot;Symptom duration in days&quot;)</code></pre>
<p><img src="review_files/figure-html/wex16-1.png" width="624" /></p>
<ul>
<li>For men, the positive relationship between sypmtom duration and the risk of disease starts to flatten then taper off after about 150 days. This is most clearly seen in the panel for men aged 60 years; there were few individuals with symptom duration greater than 150 at other ages.<br />
</li>
<li>For women, the estimated relationship between symptom duration and risk of disease was quite flat.</li>
</ul>
<hr />
<p>Use the model below to predict the probability of severe disease for a 65 year old man who has been experiencing angina for seven weeks.</p>
<div class="tutorial-exercise" data-label="wex17" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<pre class="text"><code>m8b &lt;- glm(tvdlm ~ I(age-52) + sex + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="wex17-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Apply the predict() function to a dataframe with variables age, sex and cad.dur set to the appropriate values</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="wex17-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>m8b &lt;- glm(tvdlm ~ I(age-52) + sex + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))

# Fill in the blanks
pred.dat = data.frame(age=, sex=&quot; &quot;, cad.dur=)
predict(m8b, newdata=pred.dat, type=&quot;response&quot;)</code></pre>
</div>
<div class="panel panel-default">
<div data-label="q5" class="tutorial-question panel-body">
<div id="q5-answer_container" class="shiny-html-output"></div>
<div id="q5-message_container" class="shiny-html-output"></div>
<div id="q5-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
</div>
<div id="section-calibration" class="section level3">
<h3>Calibration</h3>
<p>One way to test the calibration of the model is to check that the proportion of observed cases matches the predicted probabilities. For example, among individuals with a predicted probability of 0.50-0.60, around 55% should have severe coronary disease. The plot below shows this for 30 bins of equal size.</p>
<p><img src="review_files/figure-html/wex18-1.png" width="624" /></p>
<ul>
<li>The calibration here looks satisfactory.</li>
</ul>
<hr />
<p>The code used to create this plot is below, with some important details replaced with <strong>XXX</strong>. Can you fix the code?</p>
<div class="tutorial-exercise" data-label="wex19" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="20">
<pre class="text"><code>m8b &lt;- glm(tvdlm ~ I(age-52) + sex + cad.dur + cad.dur:sex + I(cad.dur^2) + I(cad.dur^2):sex, data=acath2, family=binomial(link=logit))

acath2 %&gt;% 
  mutate(b = predict(XXX), p = predict(XXX, type=&quot;XXX&quot;)) %&gt;% 
  group_by(cut(b, quantile(b, probs=seq(0,1,1/XXX)))) %&gt;%
  summarise(tvdlm_bin=sum(tvdlm)/n(), predprob_bin=mean(p), n_bin=n()) %&gt;%
  # add the standard error of the mean predicted probaility for each bin
  mutate(se_predprob_bin=sqrt(predprob_bin*(1 - predprob_bin)/XXX)) %&gt;%
    ggplot() + 
      geom_abline(intercept=0,slope=1, col=&quot;maroon&quot;) +
      geom_pointrange(aes(tvdlm_bin, predprob_bin,
      ymin = predprob_bin - qnorm(XXX)*se_predprob_bin,
      ymax = predprob_bin + qnorm(XXX)*se_predprob_bin)) +
      labs(x = &quot;Observed proportion of severe coronary disease&quot;, y = &quot;Predicted probability of severe coronary disease&quot;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<hr />
</div>
</div>
<div id="section-presenting-results" class="section level2">
<h2>Presenting results</h2>
<p>Thoughout this course you have learned many techniques for modelling health data. These new analytical skills are redundant, however, if you can not effectively communicate the results of your analyses to others. Presentation of results is unfortunately often overlooked, especially when students first start learning statistical methods, when the focus tends to be on models and software rather than interpretation and communication.</p>
<p>When reporting results from regression analyses we would usually include:</p>
<ul>
<li>Unadjusted and adjusted model coefficients for the variables of interest (present the raw coefficients or transformed to odds/risk/hazard ratios as appropriate)</li>
<li>Standard errors and/or confidence intervals for the coefficient estimates</li>
<li>The numbers of observations in the model</li>
<li>Summary of variables adjusted for (if they are not already in the results table)</li>
<li>Some measure of goodness-of-fit e.g. <span class="math inline">\(R^2\)</span>, AIC as appropriate</li>
</ul>
<p>It should go without saying that for any formal research it is insufficient to simply present the output from a statistical package; the analyst is also responsible for providing a clear summary and interpretation of the results. Effective communication extends to motivating and stating the aims of the analysis, and describing the data sources and statistical methods used so the analysis can be reproduced.</p>
<p>Fortunately, there are several published guidelines available for different types of studies that provide a minimum set of items that should be reported when presenting an analysis. These guidelines include the CONSORT Statement for Randomised Trials and the STROBE Statement for observational studies.</p>
<p>The <a href="http://www.equator-network.org/">Equator Network</a> provides a comprehensive, searchable database of over 400 reporting guidelines. Note that many of these guidelines are adapatations of standards such as the CONSORT or STROBE Statements tailored to specific methodologies and contexts.</p>
<hr />
<div id="section-consort-statement" class="section level4">
<h4>CONSORT Statement</h4>
<p><em><strong>C</strong>onsolidated <strong>S</strong>tandards of <strong>R</strong>eporting <strong>T</strong>rials</em></p>
<p>The CONSORT Statement was developed by the CONSORT Group to alleviate the problems arising from inadequate reporting of randomized controlled trials. The Statement comprises a 25-item checklist as well as a flow diagram template to illustrate how patients were included or excluded from the study. An example of the CONSORT flow diagram template is shown below. You can download the full checklist <a href="http://www.consort-statement.org/consort-2010">here</a> and review an example of a study reported according CONSORT guidelines <a href="http://www.consort-statement.org/examples/sample">here</a>.</p>
<div class="figure">
<img src="images/consort_flow_diagram.png" alt="" />
<p class="caption">CONSORT Flow Diagram template, downloaded from <a href="http://www.consort-statement.org" class="uri">http://www.consort-statement.org</a></p>
</div>
<hr />
</div>
<div id="section-strobe-statement" class="section level4">
<h4>STROBE Statement</h4>
<p><em><strong>ST</strong>rengthening the <strong>R</strong>eporting of <strong>OB</strong>servational studies in <strong>E</strong>pidemiology (STROBE)</em></p>
<p>The STROBE statement is a detailed checklist of items that should be reported when presenting results from an observational study. Instructions cover the title and abstract, introduction, methods, results, discussion and funding. These guidelines have been developed by an interdisciplinary collaboration of statisticians, epidemiologists, researchers and journal editors. You can download the STROBE Statement for <strong>cohort studies</strong>, <strong>case-control studies</strong> and <strong>cross-sectional studies</strong> <a href="https://www.strobe-statement.org/index.php?id=available-checklists">here</a>.</p>
<p>The RECORD Statment (<em><strong>RE</strong>porting of studies <strong>C</strong>onducted using <strong>O</strong>bservational <strong>R</strong>outinely-collected health <strong>D</strong>ata</em>) is an extension of the STROBE Statement for studies using routinely collected health data. You can download the RECORD Statement <a href="http://www.record-statement.org/checklist.php">here</a>.</p>
<hr />
</div>
<div id="section-exercise" class="section level3">
<h3>Exercise</h3>
<p>One of the best ways to learn how to present results is to read high-qualty journal publications. As an exercise, read through the published journal article linked below. As you read the paper, compare the presented results to the corresponding publication guidelines and assess whether each checklist item has been reported adequately in the study. For this exercise, just focus on the checklist items specific to the results section, i.e. items 13-17.</p>
<p>The paper for this exercise is <a href="https://jamanetwork.com/journals/jamapsychiatry/fullarticle/1743009"><em>Preterm Birth and Mortality and Morbidity: A Population-Based Quasi-experimental Study</em></a> published in 2013 in the Journal of the American Medical Association (JAMA) Psychiatry.</p>
<p>This paper examines the association between gestational age and offspring mortality, and psychiatric, academic and social outcomes in later life. The authors compare siblings born at different gestational ages in an attempt to isolate the causal effect of gestational age from other background confounding factors (factors which could simultaneously increase the risk of early gestational age and adverse outcomes).</p>
<p>As an observational cohort study using Swedish registry data, the <a href="http://www.record-statement.org/checklist.php">RECORD Statement</a> is a suitable reporting guideline.</p>
<hr />
<p>To get you started, item 13(a) of the RECORD Statement is:</p>
<ul>
<li><strong>Report the numbers of individuals at each stage of the study</strong></li>
</ul>
<p>In the Methods section, we find the following paragraph that satisfies this requirement:</p>
<blockquote>
<p><em>The present study consisted of singleton offspring born in Sweden between January 1, 1973, and December 31, 2008. Birth-related data for 3,619,712 offspring were obtained from the Swedish Medical Birth Registry. We sequentially removed multiple births (86,273), children with missing data on GA (8290), those with a recorded GA less than 23 weeks (153) or more than 42 weeks and 6 days (41,440), missing maternal identification numbers (4070), invalid or missing sex (2), invalid parity (23), and those who emigrated from Sweden (178,753) during this period. The resulting cohort of 3,300,708 offspring represents 91.2% of all recorded births to a total of 1,736,735 biological mothers. Most offspring had siblings in the data set (2,665,666 [80.8%]); they were in families of mothers (1,101,693) with more than one offspring. Sibling comparisons were made among this subset of the population.</em></p>
</blockquote>
</div>
</div>
<div id="section-q-a" class="section level2">
<h2>Q &amp; A</h2>
<p>There will be a rolling Q&amp;A on OpenLearning while this chapter is running, so please post any questions you have about the course or statistical modelling. Feel free to answer your classmates questions!</p>
<p>Congratulations on reaching the end of the last chapter and good luck for the final assessment!</p>
<hr />
<p>We’ll leave with a final thought on model fitting from the inimitable XKCD</p>
<div class="figure">
<img src="images/curve_fitting.png" alt="" />
<p class="caption">Reproduced from <a href="https://xkcd.com/2048/" class="uri">https://xkcd.com/2048/</a> (CC BY-NC 2.5)</p>
</div>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
library(Hmisc)
library(dplyr)
knitr::opts_chunk$set(echo = FALSE)
Hmisc::getHdata(acath)

acath2 = acath %>% 
  select(-choleste, -sigdz) %>% 
  filter(! is.na(tvdlm)) %>% 
  mutate(tvdlm = as.integer(tvdlm)) %>%
  mutate(sex = factor(sex, levels=c(0,1), labels = c("Male", "Female"))) %>%
  mutate(cad.dur = as.integer(cad.dur)) %>%
  mutate(age = as.integer(age))

summary(acath2)

</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = list(id = "au.edu.unsw.cbdrh.hdat9600.tutorials.review"))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-wex6-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-wex6-code-editor`)), session)
output$`tutorial-exercise-wex6-output` <- renderUI({
  `tutorial-exercise-wex6-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-wex7-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-wex7-code-editor`)), session)
output$`tutorial-exercise-wex7-output` <- renderUI({
  `tutorial-exercise-wex7-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-wex8-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-wex8-code-editor`)), session)
output$`tutorial-exercise-wex8-output` <- renderUI({
  `tutorial-exercise-wex8-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "q1", question = structure("Men are more likely than women to have severe coronary disease. By how much?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_cbfcd91",     option = "About 50% more likely", value = "About 50% more likely",     label = structure("About 50% more likely", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_f2a1a07",     option = "About twice as likely", value = "About twice as likely",     label = structure("About twice as likely", html = TRUE, class = c("html",     "character")), correct = TRUE, message = structure("39% Male versus 17% Female", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_c3603de", option = "About half as likely",     value = "About half as likely", label = structure("About half as likely", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_145a0dc",     option = "About three times more likely", value = "About three times more likely",     label = structure("About three times more likely", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "q1-answer", question = "q1"), loading = structure("<strong>Loading:<\u002fstrong> \nMen are more likely than women to have severe coronary disease. By how much?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1159092224.46026, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "q2", question = structure("Duration of symptoms is a better predictor of severe coronory disease for women compared to men?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_5d9939",     option = "True", value = "True", label = structure("True", html = TRUE, class = c("html",     "character")), correct = TRUE, message = structure("There is a stronger relationship between duration of symptoms and disease for men", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_8bf77e8", option = "False",     value = "False", label = structure("False", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_aaa801e",     option = "About the same", value = "About the same", label = structure("About the same", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("probably not", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "q2-answer", question = "q2"), loading = structure("<strong>Loading:<\u002fstrong> \nDuration of symptoms is a better predictor of severe coronory disease for women compared to men?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1579938002.26428, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-wex10-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-wex10-code-editor`)), session)
output$`tutorial-exercise-wex10-output` <- renderUI({
  `tutorial-exercise-wex10-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_checkbox", label = "q3", question = structure("Which of the following statements are true, based on the models above? (Select all that apply)", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_95209b0",     option = "There is evidence for a non-linear effect of age",     value = "There is evidence for a non-linear effect of age",     label = structure("There is evidence for a non-linear effect of age", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_b320ab4",     option = "There was a significant interaction between age and sex",     value = "There was a significant interaction between age and sex",     label = structure("There was a significant interaction between age and sex", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_2d0edff",     option = "The effect of symptom duration was linear", value = "The effect of symptom duration was linear",     label = structure("The effect of symptom duration was linear", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_54312bc",     option = "The effect of symptom duration was different for men and women",     value = "The effect of symptom duration was different for men and women",     label = structure("The effect of symptom duration was different for men and women", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_57593f5",     option = "There was a significant interaction between age and symptom duration",     value = "There was a significant interaction between age and symptom duration",     label = structure("There was a significant interaction between age and symptom duration", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_be29dfa",     option = "The effect of age was approximately linear", value = "The effect of age was approximately linear",     label = structure("The effect of age was approximately linear", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "q3-answer", question = "q3"), loading = structure("<strong>Loading:<\u002fstrong> \nWhich of the following statements are true, based on the models above? (Select all that apply)\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1570853600.76851, options = list()), class = c("learnr_checkbox", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_checkbox", label = "q4", question = structure("which models improved on the baseline model? (Select all that apply):", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_2dacf54",     option = "m2", value = "m2", label = structure("m2", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_e84484f",     option = "m3", value = "m3", label = structure("m3", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_7ae64fc",     option = "m4", value = "m4", label = structure("m4", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_7c9686b",     option = "m5", value = "m5", label = structure("m5", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_498f1d4",     option = "m6", value = "m6", label = structure("m6", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "q4-answer", question = "q4"), loading = structure("<strong>Loading:<\u002fstrong> \nwhich models improved on the baseline model? (Select all that apply):\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1071917121.50085, options = list()), class = c("learnr_checkbox", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-wex12-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-wex12-code-editor`)), session)
output$`tutorial-exercise-wex12-output` <- renderUI({
  `tutorial-exercise-wex12-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-wex17-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-wex17-code-editor`)), session)
output$`tutorial-exercise-wex17-output` <- renderUI({
  `tutorial-exercise-wex17-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "q5", question = structure("The predicted probability of severe coronary disease for a 65 year old man who has been experiencing angina for seven weeks is approximately", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_bd845",     option = "54%", value = "54%", label = structure("54%", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_eb85608",     option = "50%", value = "50%", label = structure("50%", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_6c0f228",     option = "61%", value = "61%", label = structure("61%", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_a308718",     option = "57%", value = "57%", label = structure("57%", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "q5-answer", question = "q5"), loading = structure("<strong>Loading:<\u002fstrong> \nThe predicted probability of severe coronary disease for a 65 year old man who has been experiencing angina for seven weeks is approximately\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 531841909.752342, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-wex19-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-wex19-code-editor`)), session)
output$`tutorial-exercise-wex19-output` <- renderUI({
  `tutorial-exercise-wex19-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"character","attributes":{},"value":["<style>h1 {font-size: 34px;}\n       h1.title {font-size: 38px;}\n       h2 {font-size: 30px;}\n       h3 {font-size: 24px;}\n       h4 {font-size: 18px;}\n       h5 {font-size: 16px;}\n       h6 {font-size: 12px;}\n       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}\n       pre:not([class]) { background-color: white }<\/style>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","base64enc","bslib","checkmate","cluster","colorspace","compiler","crayon","data.table","datasets","DBI","digest","dplyr","ellipsis","evaluate","fansi","farver","fastmap","foreign","Formula","generics","ggplot2","glue","graphics","grDevices","grid","gridExtra","gtable","highr","Hmisc","htmlTable","htmltools","htmlwidgets","httpuv","jpeg","jquerylib","jsonlite","knitr","labeling","later","lattice","latticeExtra","learnr","lifecycle","magrittr","markdown","Matrix","methods","mime","munsell","nnet","pillar","pkgconfig","png","promises","purrr","R6","RColorBrewer","Rcpp","rlang","rmarkdown","rpart","rprojroot","rstudioapi","sass","scales","shiny","splines","stats","stringi","stringr","survival","tibble","tidyselect","tools","utf8","utils","vctrs","withr","xfun","xtable","yaml"]},{"type":"character","attributes":{},"value":["0.2.1","1.4.1","4.0.3","0.1-3","0.3.1","2.0.0","2.1.2","2.0-2","4.0.3","1.4.2","1.14.2","4.0.3","1.1.2","0.6.29","1.0.7","0.3.2","0.14","1.0.2","2.1.0","1.1.0","0.8-82","1.2-4","0.1.1","3.3.5","1.6.0","4.0.3","4.0.3","4.0.3","2.3","0.3.0","0.9","4.6-0","2.4.0","0.5.2","1.5.4","1.6.5","0.1-9","0.1.4","1.7.3","1.37","0.4.2","1.3.0","0.20-45","0.6-29","0.10.1","1.0.1","2.0.1","1.1","1.4-0","4.0.3","0.12","0.5.0","7.3-17","1.6.4","2.0.3","0.1-7","1.2.0.1","0.3.4","2.5.1","1.1-2","1.0.7","0.4.12","2.11","4.1-15","2.0.2","0.13","0.4.0","1.1.1","1.7.1","4.0.3","4.0.3","1.7.6","1.4.0","3.2-13","3.1.6","1.1.1","4.0.3","1.2.2","4.0.3","0.3.8","2.4.3","0.29","1.8-4","2.2.1"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">HDAT9600 Course review and best practice tips</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
